// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skjtqwccuayteikonevy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNranRxd2NjdWF5dGVpa29uZXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NTE1NDQsImV4cCI6MjA1ODMyNzU0NH0.PPFd4uigsPtE1Opw5NzwspElp1H5fkabnn0bDr9bqYw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);